commun/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from commun.views import SkridaozerBookView
from commun.views import SkridaozerDeleteBookView
from commun.views import SkridaozerAddBookView
from meurgorf.views import SkridaozerMeurgorfTermView
from meurgorf.views import SkridaozerMeurgorfAddTermView
from meurgorf.views import SkridaozerMeurgorfStatView
from meurgorf.views import SkridaozerMeurgorfExportView
from meurgorf.views import SkridaozerMeurgorfSearchView
from meurgorf.views import SkridaozerMeurgorfAjaxView
from kerofis.views import SkridaozerKerofisLocationView
from kerofis.views import SkridaozerKerofisAddLocationView
from kerofis.views import SkridaozerKerofisStatView
from kerofis.views import SkridaozerKerofisExportView
from kerofis.views import SkridaozerKerofisSearchView
from kerofis.views import SkridaozerKerofisInformantView
from kerofis.views import SkridaozerKerofisExportInfoView
from kerofis.views import SkridaozerKerofisAjaxView
from kerofis.views import SkridaozerKerofisTemplateView


class LoggedMainView(LoginRequiredMixin, TemplateView):
    pass


app_name = 'skridaozer'
urlpatterns = [
    url(r'^$', LoggedMainView.as_view(template_name='semantic/skridaozer/index.html')),
    url(r'^mammennoù/(?P<book_id>\d+)?$', SkridaozerBookView.as_view(), name='mammennou'),
    url(r'^mammennoù_lemel/(?P<book_id>\d+)?$', SkridaozerDeleteBookView.as_view(), name='mammennou_lemel'),
    url(r'^mammennoù_ouzhpennan/(?P<book_id>\d+)?$', SkridaozerAddBookView.as_view(), name='mammennou_ouzhpennan'),

    url(r'meurgorf/klask', SkridaozerMeurgorfSearchView.as_view(), name='meurgorf_klask'),
    url(r'meurgorf/ouzhpennan', SkridaozerMeurgorfAddTermView.as_view(), name='meurgorf_ouzhpennan'),
    url(r'meurgorf/etrefas/(?P<term_id>\d+)?$', SkridaozerMeurgorfTermView.as_view(), name='meurgorf_etrefas'),
    url(r'meurgorf/stadegoù', SkridaozerMeurgorfStatView.as_view(), name='meurgorf_stadegou'),
    url(r'meurgorf/ezporzhiañ', SkridaozerMeurgorfExportView.as_view(), name='meurgorf_ezporzhian'),
    url(r'meurgorf/ajax/(?P<term_id>\d+)$', SkridaozerMeurgorfAjaxView.as_view(), name='meurgorf_ajax'),

    url(r'kerofis/klask', SkridaozerKerofisSearchView.as_view(), name='kerofis_klask'),
    url(r'kerofis/ouzhpennan', SkridaozerKerofisAddLocationView.as_view(), name='kerofis_ouzhpennan'),
    url(r'kerofis/titourer/(?P<informant_id>\d+)?$', SkridaozerKerofisInformantView.as_view(), name='kerofis_titourer'),
    url(r'kerofis/stadegoù', SkridaozerKerofisStatView.as_view(), name='kerofis_stadegou'),
    url(r'kerofis/Levrigoù', SkridaozerKerofisExportInfoView.as_view(), name='kerofis_levrigou'),
    url(r'kerofis/etrefas/(?P<location_id>\d+)?$', SkridaozerKerofisLocationView.as_view(), name='kerofis_etrefas'),
    url(r'kerofis/ezporzhiañ', SkridaozerKerofisExportView.as_view(), name='kerofis_ezporzhian'),
    url(r'kerofis/ajax/(?P<location_id>\d+)$', SkridaozerKerofisAjaxView.as_view(), name='kerofis_ajax'),
    url(r'kerofis/view/(?P<template>\w+)/(?P<id>\d+)?$', SkridaozerKerofisTemplateView.as_view(), name='kerofis_view')
]

config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns


from .api import api
from meurgorf import urls as meurgorf_urls
from kerofis import urls as kerofis_urls
from commun import urls as skridaozer_urls


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^skridaozer/', include(skridaozer_urls, namespace='skridaozer')),
]

if settings.DEBUG:
    # Media urls for development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', TemplateView.as_view(template_name='semantic/index.html')),
    url(r'^meurgorf/', include(meurgorf_urls)),
    url(r'^kerofis/', include(kerofis_urls))
)

kerofis/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import KerofisSearch
from .views import KerofisRedirect

urlpatterns = [
    url(
        r'^presentation$',
        TemplateView.as_view(template_name='semantic/kerofis/presentation.html'),
        name='kerofis-presentation'
    ),
    url(
        r'^savoir',
        TemplateView.as_view(template_name='semantic/kerofis/savoir.html'),
        name='kerofis-savoir'
    ),
    url(r'^(?P<location_id>\d+)?$', KerofisSearch.as_view(), name='kerofis'),
    url(r'^city/(?P<location_name>[\w \[\]]+)?$', KerofisRedirect.as_view(), name='kerofis-city')
]

kerofis/forms.py
from django.forms import ModelForm
from .models import Location


class LocationForm(ModelForm):
    class Meta:
        model = Location
        exclude = ['created_at', 'created_by', 'old_id']

kerofis/views.py
import random

from django.core.paginator import Paginator
from django.db.models import Count
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.views.generic import View
from django.urls import reverse
from django.shortcuts import redirect
from django.shortcuts import render
from django.http import JsonResponse

from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.viewsets import ModelViewSet
from rest_framework.viewsets import GenericViewSet
from rest_framework.response import Response

from commun.pagination import StandardPagination
from commun.pagination import AutoCompletePagination
from commun.views import ExportView
from commun.models import Book

from .models import Category
from .models import City
from .models import Department
from .models import Location
from .models import Informant
from .models import PhoneticTranscription
from .models import StandardizedForm
from .models import OldForm
from .models import AttestedForm
from .models import OtherForm
from .models import TermSearchQuery
from .models import PhoneticTranscriptionLink
from .filters import LocationFilter
from .forms import LocationForm
from .serializers import LocationSerializer
from .serializers import CategoryStatSerializer


OPERATIONS = {
    "pm": "icontains",
    "me": "iexact",
    "dm": "istartswith",
    "fm": "iendswith"
}


class KerofisSearch(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nb_location'] = Location.objects.count()
        context['categories'] = Category.objects.all().order_by('name_fra')
        context['cities'] = City.objects.all().order_by('name_fra')
        context['departments'] = Department.objects.all().order_by('name_fra')
        if self.request.POST:
            context['data'] = self.request.POST
        else:
            context['data'] = {'name': self.request.GET.get('search', ""), 'search_type': 'me'}
        context['page'] = self.request.POST.get('page') or 1

        queryset = None
        if self.kwargs.get('location_id'):
            queryset = Location.objects.filter(pk=self.kwargs['location_id'])
        elif self.request.POST.get('name'):
            data = self.request.POST
            operation = OPERATIONS.get(data.get('search_type'))
            queryset = Location.objects.filter(**{f'name__unaccent__{operation}': data.get('name')})

        if queryset is not None:
            paginator = Paginator(queryset.order_by('name', 'pk').distinct('name', 'pk'), 20)
            context['paginator'] = paginator
            context['locations'] = paginator.get_page(context['page'])
        else:
            locations_of_day = list(Location.objects.filter(is_name_of_day=True).all())
            if len(locations_of_day):
                context['location_of_day'] = locations_of_day[random.randint(0, len(locations_of_day) - 1)]

        return context

    def get_template_names(self):
        if self.request.POST.get('name'):
            return ['semantic/kerofis/search.html']

        if self.kwargs.get('location_id'):
            return ['semantic/kerofis/location.html']

        return ['semantic/kerofis/index.html']

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class KerofisRedirect(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        """
        Return the URL redirect to. Keyword arguments from the URL pattern
        match generating the redirect request are provided as kwargs to this
        method.
        """
        location_id = None
        location_name = kwargs.get('location_name')
        if location_name:
            print(Location.objects.filter(name=location_name).all())
            location_id = Location.objects.filter(name=location_name, category__name_fra='Commune').first().id

        return reverse('kerofis', kwargs={'location_id': location_id})


class LocationView(ModelViewSet):
    serializer_class = LocationSerializer
    model = Location
    queryset = Location.objects.all()
    filter_backends = (DjangoFilterBackend, )
    filterset_class = LocationFilter
    pagination_class = StandardPagination

    @property
    def paginator(self):
        """
        Reduce the paginator in case of autocomplete request
        """
        if not hasattr(self, '_paginator'):
            if 'autocomplete' in self.request.GET:
                self._paginator = AutoCompletePagination()
            else:
                self._paginator = self.pagination_class()

        return self._paginator


class SkridaozerKerofisLocationView(TemplateView):
    template_name = 'semantic/skridaozer/kerofis/etrefas.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['location_id'] = self.kwargs.get('location_id', '0')
        context['cities'] = City.objects.all().order_by('name_bre')
        context['categories'] = Category.objects.all().order_by('name_bre')
        context['informants'] = Informant.objects.all().order_by('first_name', 'last_name')
        context['books'] = Book.objects.all().order_by('abbrevation')
        context['books_old'] = Book.objects.filter(is_kerofis_old=True).order_by('abbrevation')

        if self.kwargs.get('location_id'):
            context['location'] = Location.objects.get(pk=self.kwargs['location_id'])

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        data = self.request.POST

        if self.kwargs.get('location_id'):
            form = LocationForm(self.request.POST, instance=context['location'])
            if form.is_valid():
                form.save()
            else:
                print(form.errors)
        else:
            obj = Location(generic_name=data['generic_name'], name=data['name'], created_by=self.request.user)
            obj.save()
            return redirect(reverse('skridaozer:kerofis_etrefas', kwargs={'location_id': obj.id}))

        return self.render_to_response(context)


class SkridaozerKerofisAddLocationView(RedirectView):
    pattern_name = 'skridaozer:kerofis_etrefas'

    def get_redirect_url(self, *args, **kwargs):
        location = Location(name=self.request.GET['name'], generic_name=self.request.GET['generic_name'])
        location.save()

        return super().get_redirect_url(location_id=location.id)


class SkridaozerKerofisStatView(TemplateView):
    template_name = 'semantic/skridaozer/kerofis/stadegou.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['stats_1'] = {
            "enrolladenn  en  diaz": [
                Location.objects.count(),
                ''
            ],
            "distagadur evit": [
                PhoneticTranscription.objects.count(),
                "{} anv-lec'h".format(Location.objects.filter(phonetic_transcriptions__isnull=False).count())
            ],
            "stumm skoueriekaet": [
                StandardizedForm.objects.count(),
                "{} %".format(round((StandardizedForm.objects.count() / Location.objects.count()) * 100, 2))
            ],
            "Aotre da embann": ['', ''],
            "Lec'hanvadurezh": [
                Location.objects.filter(is_public=True).count(),
                "{} %".format(
                    round((Location.objects.filter(is_public=True).count() / Location.objects.count()) * 100, 2)
                )
            ]
        }

        context['stats_2'] = {
            "stumm kozh testeniekaet": OldForm.objects.count(),
            "stumm  brezhoneg  testeniekaet": AttestedForm.objects.count(),
            "stumm all implijet": OtherForm.objects.count(),
            "daveenn douaroniel": Location.objects.filter(longitude__isnull=False).count(),
            "deiziad ofisielisaet": Location.objects.filter(formalized_date__isnull=False).count(),
            "ign": Location.objects.filter(on_ign=True).count(),
            "gerdarzh fra": Location.objects.filter(etymological_note_fra__isnull=False).count(),
            "gerdarzh bre": Location.objects.filter(etymological_note_bre__isnull=False).count(),
            "goulenn": TermSearchQuery.objects.count(),
            "distagadur skouer": PhoneticTranscription.objects.filter(is_standard=True).count(),
            "distagadur enrolladenn": PhoneticTranscriptionLink.objects.count()
        }

        context["dep"] = Location.objects.values('department__name_bre').annotate(locations_count=Count('id'))

        queryset = Category.objects.all()
        kwargs = {
            'context': {'request': self.request},
            'many': True
        }
        context["categories"] = CategoryStatSerializer(queryset, **kwargs).data

        return context


class SkridaozerKerofisExportView(ExportView):
    model = Location


class SkridaozerKerofisSearchView(TemplateView):
    template_name = 'semantic/skridaozer/kerofis/klask.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all().order_by('name_bre')
        context['departments'] = Department.objects.all().order_by('name_bre')

        if self.request.POST:
            context['data'] = self.request.POST
            context['page'] = self.request.POST.get('page') or 1
            data = context['data']
            filters = {}
            operation = data.get('search_type')
            if data.get('generic_name'):
                filters[f"generic_name__unaccent__{operation}"] = data['generic_name']
            if data.get('name'):
                if data.get('is_old'):
                    filters[f"old_forms__old_form__unaccent__{operation}"] = data['name']
                elif data.get('is_standardized'):

front/templates/semantic/skridaozer/kerofis/klask.html
{% extends "semantic/skridaozer/base.html" %}
{% load static %}

{% block content %}
  <p></p>
  <form class="ui form" method="POST" id="formulaire">{% csrf_token %}
    <input id="page" type="hidden" name="page" value="{{ page }}" />
    <input id="sorting_field" type="hidden" name="sorting_field" value="{{ sorting_field }}" />
    <input id="sorting_order" type="hidden" name="sorting_order" value="{{ sorting_order }}" />
    <div class="ui stackable grid">
      <div class="sixteen wide column">
        <div class="ui teal fluid inverted segment">
          <div class="inline fields">
            <div class="field">
              <label>Stagadenn</label>
              <div class="ui huge inverted input">
                <input type="text" name="generic_name" value="{{ data.generic_name }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field">
              <label>Lec’hanv</label>
              <div class="ui huge inverted input">
                <input type="text" name="name" value="{{ data.name }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field">
              <label>Gerioù-alc’hwez</label>
              <div class="ui huge inverted input">
                <input type="text" name="search_keyword" value="{{ data.search_keyword }}" onchange="reset_page()">
              </div>
            </div>
          </div>
          <div class="inline fields">
            <div class="field">
              <label>Kumun</label>
              <div class="ui huge inverted input">
                <input type="text" name="city" value="{{ data.city }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field" style="width: 100%">
                <label>Departamant</label>
                <select class="ui fluid selection dropdown clearable" name="department" id="select_department" onchange="reset_page()">
                    <option></option>
    {% for department in departments %}
                    <option value="{{ department.id }}"{% if data.department|add:"0" == department.id %} selected="selected"{% endif %}>{{ department.name_bre }}</option>
    {% endfor %}
                </select>
            </div>
            <div class="field" style="width: 100%">
              <label>Rummad</label>
              <select class="ui fluid selection dropdown clearable" name="category" id="select_category" onchange="reset_page()">
                <option></option>
  {% for category in categories %}
                <option value="{{ category.id }}"{% if data.category|add:"0" == category.id %} selected="selected"{% endif %}>{{ category.name_bre }}</option>
  {% endfor %}
              </select>
            </div>
          </div>
          <div class="inline fields">
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="search_type" value="icontains" onchange="reset_page()"{% if data.search_type == 'icontains' %} checked="checked"{% endif %}>
                <label>Ul lodenn eus an anv</label>
              </div>
            </div>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="search_type" value="iexact" onchange="reset_page()"{% if data.search_type == 'iexact' %} checked="checked"{% endif %}>
                <label>ger a-bezh</label>
              </div>
            </div>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="search_type" value="istartswith" onchange="reset_page()"{% if data.search_type == 'istartswith' %} checked="checked"{% endif %}>
                <label>Deroù ar ger</label>
              </div>
            </div>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="search_type" value="iendswith" onchange="reset_page()"{% if data.search_type == 'iendswith' %} checked="checked"{% endif %}>
                <label>Dibenn ar ger</label>
              </div>
            </div>
          </div>
          <div class="inline fields">
            <div class="field">
              <div class="ui checkbox">
                <input class="search_type" type="checkbox" name="is_old" onchange="change_search_type(this)"{% if data.is_old %} checked="checked"{% endif %}>
                <label>Er stummoù kozh kepken</label>
              </div>
            </div>
              <div class="field">
              <div class="ui checkbox">
                <input class="search_type" type="checkbox" name="is_standardized" onchange="change_search_type(this)"{% if data.is_normalized %} checked="checked"{% endif %}>
                <label>Er stummoù skoueriekaet hepken</label>
              </div>
            </div>
            <div class="field">
              <div class="ui checkbox">
                <input class="search_type" type="checkbox" name="is_attested" onchange="change_search_type(this)"{% if data.is_standardized %} checked="checked"{% endif %}>
                <label>Er stummoù testeniekaet hepken</label>
              </div>
            </div>
            <div class="field">
              <div class="ui checkbox">
                <input type="checkbox" name="display_normalized" onchange="reset_page()"{% if data.display_normalized %} checked="checked"{% endif %}>
                <label>Ar stummoù skoueriekaet</label>
              </div>
            </div>
            <div class="field">
              <div class="ui checkbox">
                <input type="checkbox" name="has_coordinated" onchange="reset_page()"{% if data.has_coordinated %} checked="checked"{% endif %}>
                <label>Gant daveennoù douaroniel</label>
              </div>
            </div>
            <div class="field">
              <div class="ui checkbox">
                <input type="checkbox" name="is_on_ign" onchange="reset_page()"{% if data.is_on_ign %} checked="checked"{% endif %}>
                <label>Kaset d’an IGN</label>
              </div>
            </div>
            <div class="field">
              <div class="ui checkbox">
                <input type="checkbox" name="is_official" onchange="reset_page()"{% if data.is_official %} checked="checked"{% endif %}>
                <label>Bet ofisialisaet</label>
              </div>
            </div>
            <div class="field">
              <div class="ui checkbox">
                <input type="checkbox" name="is_public" onchange="reset_page()"{% if data.is_public %} checked="checked"{% endif %}>
                <label>Embannet</label>
              </div>
            </div>
          </div>
          <div class="ui sixteen column centered grid">
            <div class="ui centered row">
              <div class="ui column">
                <button class="ui labeled icon button" name="button">
                  <i class="search icon"></i>Kas
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
  {% if locations %}
      <div class="sixteen wide column">
        <div class="ui teal segment" id="termenadur">
            <h4 class="ui header">{{ locations.count }} Disoc’h</h4>
            <table class="ui sortable selectable table">
              <thead>
                <tr>
                    <th data-name="generic_name"{% if sorting_field == 'generic_name' %} class="sorted {{ sorting_label }}"{% endif %}>Stagadenn</th>
                    <th data-name="name"{% if sorting_field == 'name' %} class="sorted {{ sorting_label }}"{% endif %}>Lec’hanv</th>
                    <th data-name="city__name_bre"{% if sorting_field == 'city__name_bre' %} class="sorted {{ sorting_label }}"{% endif %}>Kumun</th>
                    <th data-name="category__name_bre"{% if sorting_field == 'category__name_bre' %} class="sorted {{ sorting_label }}"{% endif %}>Rummad</th>
                    <th data-name="department__name_bre"{% if sorting_field == 'department__name_bre' %} class="sorted {{ sorting_label }}"{% endif %}>Departamant</th>
                {% if data.display_normalized %}
                    <th>Stumm skoueriekaet</th>
                {% endif %}
                {% if data.has_coordinated %}
                    <th>Daveennoù douaroniel</th>
                {% endif %}
                {% if data.is_on_ign %}
                    <th>Kaset d’an IGN</th>
                {% endif %}
                {% if data.is_official %}
                    <th>Bet ofisialisaet</th>
                {% endif %}
                {% if data.is_public %}
                    <th>Embannet</th>
                {% endif %}
                </tr>
              </thead>
              <tbody>
    {% for location in locations %}
                <tr onclick="window.open('{% url 'skridaozer:kerofis_etrefas' location.id %}', '_blank').focus();">
                    <td>{{ location.generic_name }}</td>
                    <td>{{ location.name }}</td>
                    <td>{{ location.city.name_bre }}</td>
                    <td>{{ location.category.name_bre }}</td>
                    <td>{{ location.department.name_bre }}</td>
                {% if data.display_normalized %}
                    <td>
                    {% for standardized_form in location.standardized_forms.all %}
                            <p>{{ standardized_form.standardized_form }}</p>
                    {% endfor %}
                    </td>
                {% endif %}
                {% if data.has_coordinated %}
                    <td>{% if location.longitude or location.latitude %}Ya{% else %}N'eo ket{% endif %}</td>
                {% endif %}
                {% if data.is_on_ign %}
                    <td>{% if location.on_ign %}Ya{% else %}N'eo ket{% endif %}</td>
                {% endif %}
                {% if data.is_official %}
                    <td>{% if location.formalized_date %}Ya{% else %}N'eo ket{% endif %}</td>
                {% endif %}
                {% if data.is_public %}
                    <td>{% if location.is_public %}Ya{% else %}N'eo ket{% endif %}</td>
                {% endif %}
                </tr>
    {% endfor %}
              </tbody>
            </table>
        </div>
      </div>
  {% else %}
    {% if locations.count == 0 %}
    <div class="sixteen wide column">
        <div class="ui teal segment">
            <h3>La référence n'a pas été trouvé</h3>
            <a class="ui labeled icon button"
               href="{% url 'skridaozer:kerofis_ouzhpennan' %}?generic_name={{ request.POST.generic_name }}&name={{ request.POST.name }}&">
                <i class="add icon"></i>Ouzhpennañ
            </a>
        </div>
    </div>
    {% endif %}
  {% endif %}
    </div>
  </form>
{% endblock %}

{% block content-js %}
  <script type="text/javascript">
    $(document).ready(function () {
        $('.ui.checkbox').checkbox();
        $('table thead th').on('click', function() {
            $('#sorting_field').val($(this).data('name'));
            $('#sorting_order').val($(this).hasClass('ascending') ? 'desc' : 'asc');
            $('#formulaire').submit();
        });
    });
    $('.paginator').on('click', function () {
        $('#page').val(this.dataset.value);
        $('#formulaire').submit();
    });
    function reset_page() {
        $('#page').val(1)
    }
    function change_search_type(selected) {
        $('.search_type').each(function() {
            if (this != selected) {
                $(this).prop('checked', false);
            }
        });
        reset_page();
    }
  </script>
{% endblock content-js %}

front/templates/semantic/skridaozer/kerofis/titourer.html
{% extends "semantic/skridaozer/base.html" %}
{% load static %}

{% block content %}
  <p></p>
  <form class="ui form" method="POST" id="formulaire">{% csrf_token %}
    <div class="ui stackable grid">
      <div class="sixteen wide column">
        <div class="ui teal fluid inverted segment">
          <div class="inline fields">
            <div class="field">
              <label>Anv Bihan Titourer</label>
              <div class="ui huge inverted input">
                <input type="text" name="first_name" value="{{ data.first_name }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field">
              <label>Anv Titourer</label>
              <div class="ui huge inverted input">
                <input type="text" name="last_name" value="{{ data.last_name }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field">
              <label>Lesanv</label>
              <div class="ui huge inverted input">
                <input type="text" name="surname" value="{{ data.surname }}" onchange="reset_page()">
              </div>
            </div>
          </div>
          <div class="inline fields">
            <div class="field">
              <label>Micher</label>
              <div class="ui huge inverted input">
                <input type="text" name="occupation" value="{{ data.occupation }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field">
              <label>Bloavezh ganedigezh</label>
              <div class="ui huge inverted input">
                <input type="text" name="birthdate" value="{{ data.birthdate }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field">
              <label>Lec’h ganedigezh</label>
              <div class="ui huge inverted input">
                <input type="text" name="birthplace" value="{{ data.birthplace }}" onchange="reset_page()">
              </div>
            </div>
          </div>
          <div class="inline fields">
            <div class="field">
              <label>Kumun titouret</label>
              <div class="ui huge inverted input">
                <input type="text" name="cities" value="{{ data.cities }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field">
              <label>Abaoe pegoulz er gumun</label>
              <div class="ui huge inverted input">
                <input type="text" name="arrival_date" value="{{ data.arrival_date }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field">
              <label>Notennoù</label>
              <div class="ui huge inverted input">
                <input type="text" name="notes" value="{{ data.notes }}" onchange="reset_page()">
              </div>
            </div>
          </div>
          <div class="inline fields">
            <div class="field">
              <label>Darempred</label>
              <div class="ui huge inverted input">
                <input type="text" name="contact" value="{{ data.contact }}" onchange="reset_page()">
              </div>
            </div>
          </div>
          <div class="ui sixteen column centered grid">
            <div class="ui centered row">
              <div class="ui column">
                <button class="ui labeled icon button" name="button">
  {% if data %}
                  <i class="save icon"></i>Entrenañ
  {% else %}
                  <i class="add icon"></i>Kemmañ
  {% endif %}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="sixteen wide column">
        <div class="ui teal segment" id="termenadur">
            <h4 class="ui header">Titourer</h4>
            <table class="ui selectable table">
              <thead>
                <th>nTitourer</th>
                <th>Anv Enklasker</th>
                <th>Anv Bihan Titourer</th>
                <th>Anv Titourer</th>
                <th>Kumun titouret</th>
              </thead>
              <tbody>
  {% for informant in informants %}
                <tr onclick="javascript:document.location.href = '{% url 'skridaozer:kerofis_titourer' informant.id %}'">
                  <td>{{ informant.id }}</td>
                  <td>{{ informant.interviewed_by|default:"" }}</td>
                  <td>{{ informant.first_name }}</td>
                  <td>{{ informant.last_name }}</td>
                  <td>{{ informant.cities }}</td>
                </tr>
  {% endfor %}
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </form>
{% endblock %}