commun/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from commun.views import SkridaozerBookView
from commun.views import SkridaozerDeleteBookView
from commun.views import SkridaozerAddBookView
from meurgorf.views import SkridaozerMeurgorfTermView
from meurgorf.views import SkridaozerMeurgorfAddTermView
from meurgorf.views import SkridaozerMeurgorfStatView
from meurgorf.views import SkridaozerMeurgorfExportView
from meurgorf.views import SkridaozerMeurgorfSearchView
from meurgorf.views import SkridaozerMeurgorfAjaxView
from kerofis.views import SkridaozerKerofisLocationView
from kerofis.views import SkridaozerKerofisAddLocationView
from kerofis.views import SkridaozerKerofisStatView
from kerofis.views import SkridaozerKerofisExportView
from kerofis.views import SkridaozerKerofisSearchView
from kerofis.views import SkridaozerKerofisInformantView
from kerofis.views import SkridaozerKerofisExportInfoView
from kerofis.views import SkridaozerKerofisAjaxView
from kerofis.views import SkridaozerKerofisTemplateView


class LoggedMainView(LoginRequiredMixin, TemplateView):
    pass


app_name = 'skridaozer'
urlpatterns = [
    url(r'^$', LoggedMainView.as_view(template_name='semantic/skridaozer/index.html')),
    url(r'^mammennoù/(?P<book_id>\d+)?$', SkridaozerBookView.as_view(), name='mammennou'),
    url(r'^mammennoù_lemel/(?P<book_id>\d+)?$', SkridaozerDeleteBookView.as_view(), name='mammennou_lemel'),
    url(r'^mammennoù_ouzhpennan/(?P<book_id>\d+)?$', SkridaozerAddBookView.as_view(), name='mammennou_ouzhpennan'),

    url(r'meurgorf/klask', SkridaozerMeurgorfSearchView.as_view(), name='meurgorf_klask'),
    url(r'meurgorf/ouzhpennan', SkridaozerMeurgorfAddTermView.as_view(), name='meurgorf_ouzhpennan'),
    url(r'meurgorf/etrefas/(?P<term_id>\d+)?$', SkridaozerMeurgorfTermView.as_view(), name='meurgorf_etrefas'),
    url(r'meurgorf/stadegoù', SkridaozerMeurgorfStatView.as_view(), name='meurgorf_stadegou'),
    url(r'meurgorf/ezporzhiañ', SkridaozerMeurgorfExportView.as_view(), name='meurgorf_ezporzhian'),
    url(r'meurgorf/ajax/(?P<term_id>\d+)$', SkridaozerMeurgorfAjaxView.as_view(), name='meurgorf_ajax'),

    url(r'kerofis/klask', SkridaozerKerofisSearchView.as_view(), name='kerofis_klask'),
    url(r'kerofis/ouzhpennan', SkridaozerKerofisAddLocationView.as_view(), name='kerofis_ouzhpennan'),
    url(r'kerofis/titourer/(?P<informant_id>\d+)?$', SkridaozerKerofisInformantView.as_view(), name='kerofis_titourer'),
    url(r'kerofis/stadegoù', SkridaozerKerofisStatView.as_view(), name='kerofis_stadegou'),
    url(r'kerofis/Levrigoù', SkridaozerKerofisExportInfoView.as_view(), name='kerofis_levrigou'),
    url(r'kerofis/etrefas/(?P<location_id>\d+)?$', SkridaozerKerofisLocationView.as_view(), name='kerofis_etrefas'),
    url(r'kerofis/ezporzhiañ', SkridaozerKerofisExportView.as_view(), name='kerofis_ezporzhian'),
    url(r'kerofis/ajax/(?P<location_id>\d+)$', SkridaozerKerofisAjaxView.as_view(), name='kerofis_ajax'),
    url(r'kerofis/view/(?P<template>\w+)/(?P<id>\d+)?$', SkridaozerKerofisTemplateView.as_view(), name='kerofis_view')
]

config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns


from .api import api
from meurgorf import urls as meurgorf_urls
from kerofis import urls as kerofis_urls
from commun import urls as skridaozer_urls


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^skridaozer/', include(skridaozer_urls, namespace='skridaozer')),
]

if settings.DEBUG:
    # Media urls for development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', TemplateView.as_view(template_name='semantic/index.html')),
    url(r'^meurgorf/', include(meurgorf_urls)),
    url(r'^kerofis/', include(kerofis_urls))
)

meurgorf/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import TermSearch


urlpatterns = [
    url(r'^presentation$', TemplateView.as_view(template_name='semantic/meurgorf/presentation.html')),
    url(r'^sources$', TemplateView.as_view(template_name='semantic/meurgorf/sources.html')),
    url(r'^abrev$', TemplateView.as_view(template_name='semantic/meurgorf/abrev.html')),
    url(r'^(?P<term_id>\d+)?$', TermSearch.as_view(), name='term')
]

meurgorf/forms.py
from django.forms import ModelForm
from .models import Term


class TermForm(ModelForm):
    class Meta:
        model = Term
        exclude = ['created_at', 'created_by', 'old_id', 'parents']

meurgorf/views.py
from django.db.models import Q
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.views.generic import View
from django.http import JsonResponse

from commun.views import ExportView
from commun.models import Book

from .models import DerivedForm
from .models import GrammaticalCategory
from .models import HistoricalOccurrence
from .models import PhoneticForm
from .models import Term
from .models import TermSearchQuery
from .models import Variant
from .forms import TermForm
from .utils import save_search_query
from .serializers import GrammaticalCategoryStatSerializer


OPERATIONS = {
    "pm": "icontains",
    "me": "iexact",
    "dm": "istartswith",
    "fm": "iendswith"
}


def get_related(canonic_form):
    return reversed(
        Term.objects.filter(canonic_form__lt=canonic_form).order_by('-canonic_form')[:2]
    ), Term.objects.filter(canonic_form__gt=canonic_form).order_by('canonic_form')[:3]


class TermSearch(TemplateView):
    template_name = 'semantic/meurgorf/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = GrammaticalCategory.objects.all().order_by('title_fra')
        context['books'] = Book.objects.filter(is_meurgorf=True)
        context['terms_count'] = Term.objects.count()
        if self.request.POST:
            context['data'] = self.request.POST
        else:
            context['data'] = {
                'term': self.request.GET.get('search', ""),
                'search_type': self.request.GET.get("search_type", "me")}
        context['page'] = self.request.POST.get('page') or 1

        queryset = None
        if self.kwargs.get('term_id'):
            queryset = Term.objects.filter(pk=self.kwargs['term_id'])
        elif context['data'].get('term'):
            data = context['data']
            filters = {}
            operation = OPERATIONS.get(data.get('search_type'))
            term_filter = Q(**{f"canonic_form__unaccent__{operation}": data['term']})
            term_filter |= Q(**{f"variants__variant__unaccent__{operation}": data['term']})
            if data.get('category'):
                filters['grammatical_category'] = data['category']
            if data.get('book'):
                filters['historical_occurrences__book'] = data['book']
            queryset = Term.objects.filter(term_filter, **filters)
            save_search_query(data['term'], data.get('search_type'), queryset)
        elif context['data'].get('category') and context['data'].get('book'):
            data = context['data']
            filters = {
                'grammatical_category': data['category'],
                'historical_occurrences__book': data['book']
            }
            queryset = Term.objects.filter(**filters)

        context['search_queries'] = TermSearchQuery.objects.order_by('-date')[:5]

        if queryset is not None:
            paginator = Paginator(queryset.order_by('canonic_form', 'pk').distinct('canonic_form', 'pk'), 20)
            context['paginator'] = paginator
            context['terms'] = paginator.get_page(context['page'])
            context['related_terms'] = get_related(queryset.first().canonic_form) if queryset else None

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class SkridaozerMeurgorfTermView(TemplateView):
    template_name = 'semantic/skridaozer/meurgorf/etrefas.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = GrammaticalCategory.objects.all().order_by('title_bre')
        context['books'] = Book.objects.all().order_by('abbrevation')
        context['term_id'] = self.kwargs.get('term_id', 0)
        if self.kwargs.get('term_id'):
            context['term'] = Term.objects.get(pk=self.kwargs['term_id'])
            context['related_terms'] = get_related(context['term'].canonic_form)

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        data = self.request.POST

        if self.kwargs.get('term_id'):
            form = TermForm(self.request.POST, instance=context['term'])
            if form.is_valid():
                form.save()
            else:
                print(form.errors)
        else:
            category = GrammaticalCategory.objects.get(pk=data['grammatical_category'])
            obj = Term(canonic_form=data['canonic_form'], grammatical_category=category)
            obj.save()
            return redirect(reverse('skridaozer:meurgorf_etrefas', kwargs={'term_id': obj.id}))

        return self.render_to_response(context)


class SkridaozerMeurgorfAddTermView(RedirectView):
    pattern_name = 'skridaozer:meurgorf_etrefas'

    def get_redirect_url(self, *args, **kwargs):
        try:
            category = GrammaticalCategory.objects.get(pk=self.request.GET.get('grammatical_category'))
        except (GrammaticalCategory.DoesNotExist, ValueError):
            category = GrammaticalCategory.objects.first()
        term = Term(canonic_form=self.request.GET['canonic_form'], grammatical_category=category)
        term.save()

        return super().get_redirect_url(term_id=term.id)


class SkridaozerMeurgorfStatView(TemplateView):
    template_name = 'semantic/skridaozer/meurgorf/stadegou.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['stats'] = {
            "Pennger en diaz": Term.objects.count(),
            "Stumm istorel testeniekaet": HistoricalOccurrence.objects.count(),
            "Adpennger": Variant.objects.count(),
            "Stumm deveret skouer": DerivedForm.objects.count(),
            "Stumm deveret all": DerivedForm.objects.exclude(sub_order__gt=0).count(),
            "Termenadur": Term.objects.exclude(definition__isnull=True).exclude(definition__exact='').count(),
            "Displegadur gerdarzhel": Term.objects.exclude(etymology__isnull=True).exclude(etymology__exact='').count(),
            "Notenn studiañ": Term.objects.exclude(study_notes__isnull=True).exclude(study_notes__exact='').count(),
            "Distagadur": PhoneticForm.objects.exclude(phonetic_form__isnull=True).count(),
            "Distagadur enrolladenn": PhoneticForm.objects.exclude(phonetic_file__isnull=True).count(),
            "Reket": 0
        }

        queryset = GrammaticalCategory.objects.all()
        kwargs = {
            'context': {'request': self.request},
            'many': True
        }
        context["grammatical_categories"] = GrammaticalCategoryStatSerializer(queryset, **kwargs).data

        return context


class SkridaozerMeurgorfExportView(ExportView):
    model = Term


class SkridaozerMeurgorfSearchView(TemplateView):
    template_name = 'semantic/skridaozer/meurgorf/klask.html'

    def get_context_data(self, **kwargs):
        queryset = None

        context = super().get_context_data(**kwargs)
        context['categories'] = GrammaticalCategory.objects.all().order_by('title_bre')
        context['books'] = Book.objects.exclude(title='').order_by('title')

        if self.request.POST:
            context['data'] = self.request.POST
            context['page'] = self.request.POST.get('page') or 1
            data = context['data']
            filters = {}
            operation = data.get('search_type')
            term_filter = Q(**{f"canonic_form__unaccent__{operation}": data['canonic_form']})
            term_filter |= Q(**{f"variants__variant__unaccent__{operation}": data['canonic_form']})
            if data.get('historical_occurrence'):
                filters['historical_occurrences__occurence'] = data['historical_occurrence']
            if data.get('category'):
                filters['grammatical_category'] = data['category']
            if data.get('book'):
                filters['historical_occurrences__book'] = data['book']
            queryset = Term.objects.filter(term_filter, **filters)
            paginator = Paginator(queryset.order_by('canonic_form', 'pk').distinct('canonic_form', 'pk'), 20)
            context['paginator'] = paginator
            context['terms'] = paginator.get_page(context['page'])
            context['related_terms'] = get_related(queryset.first().canonic_form) if queryset else None
        else:
            context['data'] = {'search_type': 'istartswith'}

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class SkridaozerMeurgorfAjaxView(View):

    def post(self, request, *args, **kwargs):
        try:
            action = request.POST.get('action')
            obj = Term.objects.get(pk=self.kwargs['term_id'])
            getattr(self, action)(obj, request.POST)

            return JsonResponse({"response": "ok"})
        except Exception as e:
            return JsonResponse({"response": "error", "msg": str(e)})

    def get(self, request, *args, **kwargs):
        results = []
        if request.GET.get('query'):
            for term in Term.objects.filter(canonic_form__icontains=request.GET.get('query', '')):
                results.append({
                    'id': term.id,
                    'title': term.canonic_form,
                    'description': term.grammatical_category.title_bre
                })
        return JsonResponse({'results': results})

    def add_variant(self, obj, data):
        variant = Variant(
            term=obj,
            variant=data['variant']
        )
        variant.save()

    def add_derived_form(self, obj, data):
        derived_form = DerivedForm(
            term=obj,
            order=1,

front/templates/semantic/skridaozer/meurgorf/klask.html
{% extends "semantic/skridaozer/base.html" %}
{% load static %}

{% block content %}
  <p></p>
  <form class="ui form" method="POST" id="formulaire">{% csrf_token %}
    <input id="page" type="hidden" name="page" value="{{ page }}" />
    <div class="ui stackable grid">
      <div class="sixteen wide column">
        <div class="ui teal fluid inverted segment">
          <div class="fields">
            <div class="field">
              <label>Pennger</label>
              <div class="ui huge inverted input">
                <input type="text" name="canonic_form" value="{{ data.canonic_form }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field">
              <label>Stumm istorel</label>
              <div class="ui huge inverted input">
                <input type="text" name="historical_occurrence" value="{{ data.historical_occurrence }}" onchange="reset_page()">
              </div>
            </div>
            <div class="field" style="width: 100%">
              <label>Rumenn-ger</label>
              <select class="ui fluid selection dropdown clearable" name="category" id="select_category" onchange="reset_page()">
                <option></option>
  {% for category in categories %}
                <option value="{{ category.id }}"{% if data.category == category.id %} selected="selected"{% endif %}>{{ category.title_bre }}</option>
  {% endfor %}
              </select>
            </div>
          </div>
          <div class="inline fields">
            <div class="field">
              <div class="ui floating dropdown clearable labeled icon button" id="select_book" onchange="reset_page()">
                <input type="hidden" name="book" value="{{ data.book }}">
                <i class="book icon"></i>
                <span class="text">Oberenn</span>
                <div class="menu">
                  <div class="ui icon search input">
                    <i class="search icon"></i>
                    <input type="text" placeholder="Rechercher un livre">
                  </div>
                  <div class="scrolling menu">
                    <div class="item" data-text="Oberenn" data-value=""></div>
    {% for book in books %}
                    <div class="item" data-value="{{ book.id }}">{{ book.title }}</div>
    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="inline fields">
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="search_type" value="icontains" onchange="reset_page()"{% if data.search_type == 'icontains' %} checked="checked"{% endif %}>
                <label>Darn eus ar ger</label>
              </div>
            </div>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="search_type" value="iexact" onchange="reset_page()"{% if data.search_type == 'iexact' %} checked="checked"{% endif %}>
                <label>ger a-bezh</label>
              </div>
            </div>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="search_type" value="istartswith" onchange="reset_page()"{% if data.search_type == 'istartswith' %} checked="checked"{% endif %}>
                <label>Deroù ar ger</label>
              </div>
            </div>
            <div class="field">
              <div class="ui radio checkbox">
                <input type="radio" name="search_type" value="iendswith" onchange="reset_page()"{% if data.search_type == 'iendswith' %} checked="checked"{% endif %}>
                <label>Dibenn ar ger</label>
              </div>
            </div>
          </div>
          <div class="ui sixteen column centered grid">
            <div class="ui centered row">
              <div class="ui column">
                <button class="ui labeled icon button" name="button">
                  <i class="search icon"></i>Kas
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
  {% if terms %}
      <div class="sixteen wide column">
        <div class="ui teal segment" id="termenadur">
            <h4 class="ui header">Disoc’h : {{ terms.start_index }}-{{ terms.end_index }} - Page {{ page }}/{{ paginator.num_pages }} </h4>
            <table class="ui selectable table">
              <tbody>
    {% for term in terms %}
                <tr onclick="javascript:document.location.href = '{% url 'skridaozer:meurgorf_etrefas' term.id %}'">
                  <td>{{ term.canonic_form }}</td>
                  <td>{{ term.grammatical_category.title_bre }}</td>
                </tr>
    {% endfor %}
                <tr>
                  <td colspan="2">
                    <div class="ui right floated pagination menu">
    {% if terms.has_previous %}
                      <a data-value="1" class="icon item paginator">
                        <i class="angle double left icon"></i>
                      </a>
                      <a data-value="{{ terms.previous_page_number }}" class="icon item paginator">
                        <i class="left chevron icon"></i>
                      </a>
                      <div class="ui floating dropdown icon button">
                        <span class="text">...</span>
                        <div class="menu">
      {% for page_number in paginator.page_range %}
        {% if page_number < terms.number %}
                          <div data-value="{{ page_number }}" class="item paginator">{{ page_number }}</div>
        {% endif %}
      {% endfor %}
                        </div>
                      </div>
    {% endif %}
                      <a data-value="{{ terms.number }}" class="item paginator active">{{ terms.number }}</a>
    {% if terms.has_next %}
                      <div class="ui floating dropdown icon button">
                        <span class="text">...</span>
                        <div class="menu">
      {% for page_number in paginator.page_range %}
        {% if page_number > terms.number %}
                          <div data-value="{{ page_number }}" class="item paginator">{{ page_number }}</div>
        {% endif %}
      {% endfor %}
                        </div>
                      </div>
                      <a data-value="{{ terms.next_page_number }}" class="icon item paginator">
                        <i class="right chevron icon"></i>
                      </a>
                      <a data-value="{{ paginator.num_pages }}" class="icon item paginator">
                        <i class="angle double right icon"></i>
                      </a>
    {% endif %}
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
        </div>
      </div>
    {% else %}
        {% if terms.end_index == 0 %}
    <div class="sixteen wide column">
        <div class="ui teal segment">
            <h3>La référence n'a pas été trouvé</h3>
            <a class="ui labeled icon button"
               href="{% url 'skridaozer:meurgorf_ouzhpennan' %}?canonic_form={{ request.POST.canonic_form }}&grammatical_category={{ request.POST.category }}">
                <i class="add icon"></i>Ouzhpennañ
            </a>
        </div>
    </div>
        {% endif %}
    {% endif %}
    </div>
  </form>
{% endblock %}

{% block content-js %}
  <script type="text/javascript">
    $('.paginator').on('click', function () {
        $('#page').val(this.dataset.value);
        $('#formulaire').submit();
    });
    function reset_page() {
        $('#page').val(1)
    }
  </script>
{% endblock content-js %}

front/templates/semantic/skridaozer/meurgorf/stadegou.html
{% extends "semantic/skridaozer/base.html" %}
{% load static %}

{% block content %}
<p></p>
<div class="ui stackable grid">
    <div class="eight wide column">
      <div class="ui teal segment">
        <table class="ui very basic table">
            <tbody>
    {% for libelle, stat in stats.items %}
        <tr>
            <td>{{ libelle }}</td>
            <td>{{ stat }}</td>
        </tr>
    {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
    <div class="eight wide column">
      <div class="ui teal segment">
        <table class="ui very basic table">
            <tbody>
    {% for grammatical_category in grammatical_categories %}
            <tr>
                <td>{{ grammatical_category.title }}</td>
                <td>{{ grammatical_category.terms_count }}</td>
                <td>{{ grammatical_category.percent }} %</td>
            </tr>
    {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
</div>
{% endblock %}