commun/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from commun.views import SkridaozerBookView
from commun.views import SkridaozerDeleteBookView
from commun.views import SkridaozerAddBookView
from meurgorf.views import SkridaozerMeurgorfTermView
from meurgorf.views import SkridaozerMeurgorfAddTermView
from meurgorf.views import SkridaozerMeurgorfStatView
from meurgorf.views import SkridaozerMeurgorfExportView
from meurgorf.views import SkridaozerMeurgorfSearchView
from meurgorf.views import SkridaozerMeurgorfAjaxView
from kerofis.views import SkridaozerKerofisLocationView
from kerofis.views import SkridaozerKerofisAddLocationView
from kerofis.views import SkridaozerKerofisStatView
from kerofis.views import SkridaozerKerofisExportView
from kerofis.views import SkridaozerKerofisSearchView
from kerofis.views import SkridaozerKerofisInformantView
from kerofis.views import SkridaozerKerofisExportInfoView
from kerofis.views import SkridaozerKerofisAjaxView
from kerofis.views import SkridaozerKerofisTemplateView


class LoggedMainView(LoginRequiredMixin, TemplateView):
    pass


app_name = 'skridaozer'
urlpatterns = [
    url(r'^$', LoggedMainView.as_view(template_name='semantic/skridaozer/index.html')),
    url(r'^mammennoù/(?P<book_id>\d+)?$', SkridaozerBookView.as_view(), name='mammennou'),
    url(r'^mammennoù_lemel/(?P<book_id>\d+)?$', SkridaozerDeleteBookView.as_view(), name='mammennou_lemel'),
    url(r'^mammennoù_ouzhpennan/(?P<book_id>\d+)?$', SkridaozerAddBookView.as_view(), name='mammennou_ouzhpennan'),

    url(r'meurgorf/klask', SkridaozerMeurgorfSearchView.as_view(), name='meurgorf_klask'),
    url(r'meurgorf/ouzhpennan', SkridaozerMeurgorfAddTermView.as_view(), name='meurgorf_ouzhpennan'),
    url(r'meurgorf/etrefas/(?P<term_id>\d+)?$', SkridaozerMeurgorfTermView.as_view(), name='meurgorf_etrefas'),
    url(r'meurgorf/stadegoù', SkridaozerMeurgorfStatView.as_view(), name='meurgorf_stadegou'),
    url(r'meurgorf/ezporzhiañ', SkridaozerMeurgorfExportView.as_view(), name='meurgorf_ezporzhian'),
    url(r'meurgorf/ajax/(?P<term_id>\d+)$', SkridaozerMeurgorfAjaxView.as_view(), name='meurgorf_ajax'),

    url(r'kerofis/klask', SkridaozerKerofisSearchView.as_view(), name='kerofis_klask'),
    url(r'kerofis/ouzhpennan', SkridaozerKerofisAddLocationView.as_view(), name='kerofis_ouzhpennan'),
    url(r'kerofis/titourer/(?P<informant_id>\d+)?$', SkridaozerKerofisInformantView.as_view(), name='kerofis_titourer'),
    url(r'kerofis/stadegoù', SkridaozerKerofisStatView.as_view(), name='kerofis_stadegou'),
    url(r'kerofis/Levrigoù', SkridaozerKerofisExportInfoView.as_view(), name='kerofis_levrigou'),
    url(r'kerofis/etrefas/(?P<location_id>\d+)?$', SkridaozerKerofisLocationView.as_view(), name='kerofis_etrefas'),
    url(r'kerofis/ezporzhiañ', SkridaozerKerofisExportView.as_view(), name='kerofis_ezporzhian'),
    url(r'kerofis/ajax/(?P<location_id>\d+)$', SkridaozerKerofisAjaxView.as_view(), name='kerofis_ajax'),
    url(r'kerofis/view/(?P<template>\w+)/(?P<id>\d+)?$', SkridaozerKerofisTemplateView.as_view(), name='kerofis_view')
]

config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns


from .api import api
from meurgorf import urls as meurgorf_urls
from kerofis import urls as kerofis_urls
from commun import urls as skridaozer_urls


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^skridaozer/', include(skridaozer_urls, namespace='skridaozer')),
]

if settings.DEBUG:
    # Media urls for development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', TemplateView.as_view(template_name='semantic/index.html')),
    url(r'^meurgorf/', include(meurgorf_urls)),
    url(r'^kerofis/', include(kerofis_urls))
)

front/templates/semantic/skridaozer/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Skridaozer</title>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
  <script src="{% static 'commun/semantic/dist/semantic.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'commun/semantic/mystyle.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'commun/semantic/dist/semantic.min.css' %}">
  <style>
    .ui.sidebar {
      overflow: visible !important;
    }
  </style>
</head>

<body>
  <div class="ui left vertical sidebar menu overlay visible">
    <div class="item">
      <img src="{% static 'commun/images/logo_new.png' %}" />
    </div>
    <a class="item" href="{% url 'skridaozer:mammennou' %}">
      Mammennoù
    </a>
    <div class="ui dropdown item">
      <i class="dropdown icon"></i>
      Meurgorf
      <div class="menu">
        <a
          class="item{% if request.resolver_match.url_name == 'meurgorf_klask' %} active selected{% endif %}"
          href="{% url 'skridaozer:meurgorf_klask' %}">Klask</a>
        <a
          class="item{% if request.resolver_match.url_name == 'meurgorf_stadegou' %} active selected{% endif %}"
          href="{% url 'skridaozer:meurgorf_stadegou' %}">Stadegoù</a>
        <a
          class="item{% if request.resolver_match.url_name == 'meurgorf_ezporzhian' %} active selected{% endif %}"
          href="{% url 'skridaozer:meurgorf_ezporzhian' %}">Ezporzhiañ</a>
      </div>
    </div>
    <div class="ui dropdown item">
      <i class="dropdown icon"></i>
      Kerofis
      <div class="menu">
        <a
           class="item{% if request.resolver_match.url_name == 'kerofis_klask' %} active selected{% endif %}"
           href="{% url 'skridaozer:kerofis_klask' %}">Klask</a>
        <a
           class="item{% if request.resolver_match.url_name == 'kerofis_titourer' %} active selected{% endif %}"
           href="{% url 'skridaozer:kerofis_titourer' %}">Titourer</a>
        <a
           class="item{% if request.resolver_match.url_name == 'kerofis_stadegou' %} active selected{% endif %}"
           href="{% url 'skridaozer:kerofis_stadegou' %}">Stadegoù</a>
        <a
           class="item{% if request.resolver_match.url_name == 'kerofis_levrigou' %} active selected{% endif %}"
           href="{% url 'skridaozer:kerofis_levrigou' %}">Levrigoù</a>
        <a
           class="item{% if request.resolver_match.url_name == 'kerofis_ezporzhian' %} active selected{% endif %}"
           href="{% url 'skridaozer:kerofis_ezporzhian' %}">Ezporzhiañ</a>
      </div>
    </div>
  </div>
  <div class="ui container" id="skridaozer">{% block content %}{% endblock content %}</div>

  <script type="text/javascript">
    $('.ui.left.sidebar').sidebar({
        transition: 'overlay'
    });
    $('.ui.left.sidebar').sidebar('attach events', '.open.button');
    $('.ui .dropdown:not(.notclearable)').dropdown();
    $('.ui .dropdown.clearable').dropdown({ clearable: true });
  </script>
  {% block content-js %}{% endblock content-js %}
</body>
</html>

front/templates/semantic/skridaozer/index.html
{% extends "semantic/skridaozer/base.html" %}
{% load static %}

{% block content %}
{% endblock %}

front/templates/semantic/skridaozer/mammennoù.html
{% extends "semantic/skridaozer/base.html" %}
{% load static %}

{% block content %}
  <p></p>
  <form class="ui form" method="{% if book %}post{% else %}get{% endif %}" id="formulaire">
  {% if book %}
    {% csrf_token %}
    <div class="ui right close rail">
      <div class="ui sticky" style="width: 272px !important; height: 262.683px !important; left: 164px;">
        <p></p>
        <div class="ui compact segment">
          <button class="ui teal labeled icon button" name="button" type="submit">
            <i class="save icon"></i>Enrollañ
          </button>

          <p></p>
          <a class="ui negative labeled icon button" name="button" href="{% url 'skridaozer:mammennou' %}">
            <i class="delete icon"></i>Dilemel
          </a>
        </div>
      </div>
    </div>
  {% endif %}
    <div class="ui stackable grid">
  {% if book %}
      <div class="sixteen wide column">
        <div class="ui teal fluid segment">
          <div class="row fields">
            <div class="field">
              <label>Berradur</label>
                <div class="ui huge inverted input">
                  <input type="text" name="abbrevation" value="{{ book.abbrevation }}">
                </div>
            </div>
            <div class="field" style="width: 100%;">
              <label>Levr</label>
                <div class="ui huge inverted input">
                  <input type="text" name="title" value="{{ book.title }}">
                </div>
            </div>
          </div>
          <div class="row fields">
            <div class="field">
              <label>Aozer</label>
                <div class="ui huge inverted input">
                  <input type="text" name="author" value="{{ book.author }}">
                </div>
            </div>
            <div class="field" style="width: 100%;">
              <label>Deskrivadur</label>
                <div class="ui huge inverted input">
                  <input type="text" name="description" value="{{ book.description }}">
                </div>
            </div>
          </div>
          <div class="row fields">
            <div class="field">
              <label>Stummoù kozh</label>
                <div class="ui huge inverted input">
                  <input type="checkbox" name="is_kerofis_old" {% if book.is_kerofis_old %}checked="checked"{% endif %}>
                </div>
            </div>
            <div class="field">
              <label>Stummoù all</label>
                <div class="ui huge inverted input">
                  <input type="checkbox" name="is_kerofis_other" {% if book.is_kerofis_other %}checked="checked"{% endif %}>
                </div>
            </div>
            <div class="field">
              <label>Stummoù testeniekaet</label>
                <div class="ui huge inverted input">
                  <input type="checkbox" name="is_kerofis_attested" {% if book.is_kerofis_attested %}checked="checked"{% endif %}>
                </div>
            </div>
            <div class="field">
              <label>Meurgorf</label>
                <div class="ui huge inverted input">
                  <input type="checkbox" name="is_meurgorf" {% if book.is_meurgorf %}checked="checked"{% endif %}>
                </div>
            </div>
            <div class="field">
              <label>Bev</label>
                <div class="ui huge inverted input">
                  <input type="checkbox" name="is_active" {% if book.is_active %}checked="checked"{% endif %}>
                </div>
            </div>
          </div>
        </div>
      </div>
  {% else %}
      <div class="eight wide column">
        <div class="ui middle aligned centered grid teal fluid inverted segment">
          <div class="row">
            <div class="column">
              <div class="field">
                <label>Berradur</label>
                <div class="ui huge inverted input">
                  <input type="text" name="abbrevation" value="">
                </div>
              </div>
              <div class="field">
                <label>Levr</label>
                <div class="ui huge inverted input">
                  <input type="text" name="title" value="">
                </div>
              </div>
              <div class="field">
                <button class="ui labeled icon button" name="button">
                  <i class="search icon"></i>Kas
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
  {% endif %}
  {% if books %}
      <div class="sixteen wide column">
        <div class="ui teal segment">
          <table class="ui very basic table">
            <thead>
              <tr>
                <th>Berradur</th>
                <th>Levr</th>
                <th>&nbsp;</th>
              </tr>
            </thead>
            <tbody>
            {% for book in books %}
              <tr>
                <td class="selectable{% if not book.is_active %} grey-text{% endif %}">
                  <a href="{% url 'skridaozer:mammennou' book.id %}">{{ book.abbrevation }}</a>
                </td>
                <td class="selectable{% if not book.is_active %} grey-text{% endif %}">
                  <a href="{% url 'skridaozer:mammennou' book.id %}">{{ book.title }}</a>
                </td>
                <td>
                  <a href="{% url 'skridaozer:mammennou_lemel' book.id %}" class="ui icon button">
                    <i class="trash icon"></i>
                  </a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
  {% else %}
      <div class="sixteen wide column">
        <div class="ui teal segment">
          <h3>La référence n'a pas été trouvé</h3>
          <a href="{% url 'skridaozer:mammennou_ouzhpennan' %}?abbrevation={{ request.GET.abbrevation }}" class="ui labeled icon button">
                  <i class="add icon"></i>Ouzhpennañ
          </a>
        </div>
      </div>
  {% endif %}
    </div>
  </form>
  <style>
    .grey-text {
      color: rgba(40,40,40,.3);
    }
  </style>
{% endblock %}